Counter button SFC
js-tasks-ru/vue-20210304_is pull request #5
Opened 2021-03-26 09:02 UTC by invinsible

2021-03-26 09:03 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-03-26 10:33 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2021-03-26 13:03 UTC, ShGKme reviewed
Все задачи приняты, но требуется обновить репозиторий (`git pull upstream master`)

2021-03-26 13:19 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-03-26 13:35 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-03-26 16:39 UTC, ShGKme requested changes
Требуется маленькое исправление в 01-CounterButton-vue. Компонент с моделью не работает

2021-03-26 16:39 UTC, ShGKme commented on 03-sfc/01-CounterButton-vue/components/CounterButton.vue
> +    event: 'click',
Событие модели здесь не `click`. Компонент при изменении значения порождает другое событие...

2021-03-26 16:39 UTC, ShGKme commented on 03-sfc/03-TheToaster/components/ToasterItem.vue
> +        success: Boolean
Такое решение будет работать только для бинарных тостов. Для добавления новых типов тостов придётся изменять подход...

2021-03-29 12:45 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-03-29 16:57 UTC, ShGKme requested changes
Модель в 03-sfc/01-CounterButton-vue по-прежнему не работает...

2021-03-29 16:57 UTC, ShGKme commented on 03-sfc/01-CounterButton-vue/components/CounterButton.vue
> +    event: 'change',
Модель на компоненте всё ещё не работает. Компонент порождает событие `increment` при изменении значения, а не `change`

2021-03-29 16:57 UTC, ShGKme commented on 03-sfc/03-TheToaster/components/ToasterItem.vue
> +        success: Boolean,
Этот входной параметр не используется

2021-03-29 16:57 UTC, ShGKme commented on 03-sfc/03-TheToaster/components/ToasterItem.vue
> +            default: 'alert-circle'
`required` и `default` обычно одновременно не нужны. Значение по умолчанию используется, когда никакое значение не передано, в то время как required: true говорит о том, что значение обязательно должно быть передано. Хотя можно добавить значение по умолчанию "на всякий случай".

2021-03-30 09:48 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-03-30 12:55 UTC, ShGKme approved these changes
Все-все задачи приняты🎉

2021-03-30 12:56 UTC, merged